// Build information, automatically generated by `ng-info`
const build = {
    version: "0.0.0",
    timestamp: "Thu Aug 10 2023 20:44:49 GMT+0200 (Mitteleuropäische Sommerzeit)",
    message: null,
    git: {
        user: "Torsten Kunkel",
        branch: "master",
        hash: "4209fe",
        fullHash: "4209fecdf3b3c0674e79ab697a227996f3b107a9"
    }
};

export default build;